#!/usr/bin/env python3
import argparse
import sys

import cleaner
from notifier import mark_notified, pending_from_csv, send_notification


def build_parser():
    parser = argparse.ArgumentParser(description="DHIS2 file garbage remover and notifier.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    cleanup = subparsers.add_parser("cleanup", help="Move/cleanup orphaned file resources and archive DB entries.")
    cleanup.add_argument("--force", action="store_true", help="Apply changes: move files and modify DB.")
    cleanup.add_argument("--test", action="store_true", help="Run in dry-run mode (default unless --force).")
    cleanup.add_argument("--config", required=True, help="Path to config.json file.")
    cleanup.add_argument("--csv-path", help="Optional CSV file to record processed entries.")
    cleanup.add_argument("--maintain-csv", action="store_true", help="Keep CSV contents even in --force mode (append only).")
    cleanup.add_argument("--mode", choices=["tomcat", "docker"], default="tomcat", help="Cleanup mode: tomcat (default) or docker.")
    cleanup.add_argument("--docker-instance", help="d2-docker instance name (required for --mode=docker).")

    notify = subparsers.add_parser("notify", help="Print recent, non-notified filenames from CSV and mark them notified.")
    notify.add_argument("--csv-path", required=True, help="Path to the CSV generated by cleanup.")
    notify.add_argument("--webhook-url", help="Webhook URL to send the notification.")
    notify.add_argument("--title", help="Notification title (required if --webhook-url).")
    notify.add_argument("--http-proxy", help="HTTP proxy (optional).")
    notify.add_argument("--https-proxy", help="HTTPS proxy (optional).")

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "cleanup":
        cleaner.run_cleanup(args)
        return

    if args.command == "notify":
        names, ids, fieldnames, rows = pending_from_csv(args.csv_path)
        if not names:
            sys.exit(1)
        content = "\n".join(names)
        if args.webhook_url:
            if not args.title:
                print("❌ --title is required when using --webhook-url", file=sys.stderr)
                sys.exit(1)
            try:
                send_notification(
                    webhook_url=args.webhook_url,
                    title=args.title,
                    content=content,
                    http_proxy=args.http_proxy,
                    https_proxy=args.https_proxy,
                )
            except Exception as e:
                print(f"❌ Failed to send notification: {e}", file=sys.stderr)
                sys.exit(1)
        else:
            for name in names:
                print(name)
        mark_notified(args.csv_path, rows, fieldnames, ids)
        sys.exit(0)

    parser.print_help()
    sys.exit(1)


if __name__ == "__main__":
    main()
